language: php

php:
  - 5.5
  - 5.6

branches:
  only:
    - master
    - klein

before_script:
  - composer self-update
  - wget -q -O - https://raw.github.com/DaneEveritt/roundsman/master/travis-phing.sh

script:
    - ./travis-phing.sh

install:
  - composer install --prefer-source --no-interaction --dev

notifications:
  irc:
    channels:
      - "irc.esper.net#pufferpanel"
    template:
      - "%{branch} (%{commit}): %{message} %{build_url}"
    skip_join: true
