language: go

go:
  - 1.9.x

env:
  - GO_ENV=test

addons:
  mariadb: '10.0'

before_script:
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS pufferpanel;'
  - mysql -e 'GRANT ALL PRIVILEGES ON pufferpanel.* TO pufferpanel@127.0.0.1 IDENTIFIED BY `pufferpanel`;'

go_import_path: github.com/pufferpanel/pufferpanel

install:
  - go get github.com/gobuffalo/buffalo/buffalo
  - go get $(go list ./... | grep -v /vendor/)

script: buffalo test
