dist: trusty
sudo: false

language: go
go:
  - 1.8.x

go_import_path: github.com/pufferpanel/pufferpanel

env:
- GO_ENV=test

services:
  - mysql

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable

before_script:
  - psql -c 'create database pufferpanel_test;' -U postgres
  - mysql -u root -e 'CREATE DATABASE pufferpanel_test;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets
  - go get -u -v github.com/gobuffalo/buffalo/buffalo

script:
  - cd $TRAVIS_BUILD_DIR
  - npm install
  - buffalo db create -e test
  - buffalo db migrate
  - buffalo build
