language: php

php:
  - 5.5
  - 5.6

branches:
  only:
    - master
    - klein

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: find . -name \*.php -not -path "./vendor/*" -exec php -l -f "{}" \;

install:
  - composer install

notifications:
  irc: "irc.esper.net#pufferpanel"