language: go
env:
- GO_ENV=test

services:
  - mysql

before_script:
  - psql -c 'create database pufferpanel_test;' -U postgres
  - mysql -e 'CREATE DATABASE pufferpanel_test;'
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets
  - go get -u -v github.com/gobuffalo/buffalo/buffalo

node_js:
  - "7"

go:
  - 1.8.x

go_import_path: github.com/pufferpanel/pufferpanel

script: cd $TRAVIS_BUILD_DIR && GO_ENV=test buffalo setup && buffalo build
